env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - 'airbnb'
  - 'prettier'
  - 'prettier/react'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - prettier
rules:
  react/prop-types: 0
  prettier/prettier:
    - error
    - endOfLine: lf
      semi: true
      singleQuote: true
      tabWidth: 2
      trailingComma: es5
